spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/main?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
   show-sql: false
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQLDialect
     flushMode: AUTO
     ddl-auto: validate